/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { SikhName } from './types';

export const POPULAR_SIKH_NAMES: SikhName[] = [
  {
    id: '1',
    name: 'Arjan',
    punjabiName: 'ਅਰਜਨ',
    meaning: 'Noble, Honorable, Peace-loving',
    urduMeaning: 'شریف، معزز، امن پسند اور بلند مرتبہ (Guru Arjan Dev Ji se mansoob)',
    gender: 'boy',
    startLetter: 'A',
    rashi: 'Mesha (Aries)',
    nakshatra: 'Krittika',
    personalityEffect: 'Brings immense leadership skills and a spiritual calmness to the child. Governed by Mars and Sun, the child grows up brave but extremely patient in difficult hours.',
    urduPersonalityEffect: 'Is naam se bache mein leadership aur sabr paidah hota hai. Suraj aur mreekh ke asraat ki wajah se bacha bahadur aur pur-sakoon shakhsiyat ka malik banta hai.',
    isPopular2026: true
  },
  {
    id: '2',
    name: 'Mehar',
    punjabiName: 'ਮੇਹਰ',
    meaning: 'Kindness, Grace, Blessing of Guru',
    urduMeaning: 'رحمت، مہربانی، شفق اور گورو کی بخشش',
    gender: 'girl',
    startLetter: 'M',
    rashi: 'Simha (Leo)',
    nakshatra: 'Magha',
    personalityEffect: 'Instills deep empathy, artistic elegance, and a healing vibration. The child is blessed with excellent communication skills and stands out in social circles.',
    urduPersonalityEffect: 'Sitare Magha ke asar se bachi nihayat rahamdil, saleha aur fanoon (arts) se lagao rakhne wali hoti hai. Har dil aziz aur dosron par meharban shakhsiyat banti hai.',
    isPopular2026: true
  },
  {
    id: '3',
    name: 'Fateh',
    punjabiName: 'ਫਤਿਹ',
    meaning: 'Victory, Triumphant, Conqueror',
    urduMeaning: 'فتح، کامیابی، ہر میدان میں سرخرہ ہونا',
    gender: 'boy',
    startLetter: 'F',
    rashi: 'Dhanu (Sagittarius)',
    nakshatra: 'Purvashada',
    personalityEffect: 'Creates an unbreakable willpower and high confidence. Attuned to Jupiter, the child overcomes obstacles easily and is highly competitive, destined to lead.',
    urduPersonalityEffect: 'Mushtari (Jupiter) ke asraat ki wajah se is bache mein muqabla karne ki zabardast salahiyat aur jeetne ka jazba hota hai. Mushkilaat par jald qabu pa leta hai.',
    isPopular2026: true
  },
  {
    id: '4',
    name: 'Reet',
    punjabiName: 'ਰੀਤ',
    meaning: 'Tradition, Beautiful Custom, Ritual',
    urduMeaning: 'رواج، خوبصورت روایت، طریقہ اور تہذیب',
    gender: 'girl',
    startLetter: 'R',
    rashi: 'Tula (Libra)',
    nakshatra: 'Chitra',
    personalityEffect: 'Governed by Venus (Zuhra), it grants outstanding beauty, creativity, and balance. The child resolves conflicts gracefully and maintains harmony in the family.',
    urduPersonalityEffect: 'Sitare Zuhra (Venus) ke asraat se is bachi mein shistagi aur khubsurti paidah hoti hai. Khandan mein sukoon aur rishton mein tawazun barqarar rakhne ka baais banti hai.',
    isPopular2026: true
  },
  {
    id: '5',
    name: 'Kabir',
    punjabiName: 'ਕਬੀਰ',
    meaning: 'The Great, Powerful, Spiritual Leader',
    urduMeaning: 'عظیم، بڑا، جلال والا، صوفیانہ مزاج کا مالک',
    gender: 'boy',
    startLetter: 'K',
    rashi: 'Mithuna (Gemini)',
    nakshatra: 'Ardra',
    personalityEffect: 'Promotes deep intellectual curiosity, eloquence, and philosophical thinking. Under Mercury, the child has sharp analytical mind and unique thinking abilities.',
    urduPersonalityEffect: 'Utarid (Mercury) ki badaulat bache ka zahan nihayat tez aur falsafiyana hota hai. Gafloogo aur maloomat ko samajhne mein bacha boht outstanding rehta hai.',
    isPopular2026: true
  },
  {
    id: '6',
    name: 'Ekam',
    punjabiName: 'ਏਕਮ',
    meaning: 'Oneness, Single Minded, First-born',
    urduMeaning: 'ایک ہونا، توحید، یکسوئی اور خدا کے ساتھ ایک مل جانا',
    gender: 'unisex',
    startLetter: 'E',
    rashi: 'Mesha (Aries)',
    nakshatra: 'Bharani',
    personalityEffect: 'Vibrates on unity and absolute focus. Gives the child high determination, independence, and an innovative, trend-setting mind.',
    urduPersonalityEffect: 'Infradiat aur yaksoi ka sitara hai. Bacha khud-mukhtar hota hai aur kisi par bojh nahi banta. Naye raste khud nikalne ka dharmi hota hai.',
    isPopular2026: true
  },
  {
    id: '7',
    name: 'Gurjot',
    punjabiName: 'ਗੁਰਜੋਤ',
    meaning: 'Light of the Guru, Divine Flame',
    urduMeaning: 'گورو کا نور، الہی روشنی، روحانی چمک',
    gender: 'boy',
    startLetter: 'G',
    rashi: 'Makar (Capricorn)',
    nakshatra: 'Uttarashada',
    personalityEffect: 'A very spiritual and wise vibration. Saturn holds their focus, ensuring disciplined learning, high ethics, and respect from elders.',
    urduPersonalityEffect: 'Zuhal (Saturn) ke asar se bacha ba-asool, mehnati aur darmand parhezgar hota hai. Sharafat aur barron ki izzat karne wala ba-roob bacha banta hai.',
    isPopular2026: true
  },
  {
    id: '8',
    name: 'Nimrat',
    punjabiName: 'ਨਿਮਰਤ',
    meaning: 'Humility, Humble, Grounded spirit',
    urduMeaning: 'عاجزی، انکساری، عاجز مزاجی اور گناہوں سے پاک شبیہ',
    gender: 'girl',
    startLetter: 'N',
    rashi: 'Vrishabha (Taurus)',
    nakshatra: 'Rohini',
    personalityEffect: 'Infuses extreme sweetness and deep humility in character. Under Moon, the child is natural caretaker, highly trusted, and blessed with material comfort.',
    urduPersonalityEffect: 'Chand aur Rohini sitare ke asar se bachi mein behad mithaas aur narmi paidah hoti hai. Wo khandan ke liye barkat aur sakoon ka sabab banti hai.',
    isPopular2026: true
  },
  {
    id: '9',
    name: 'Tegbir',
    punjabiName: 'ਤੇਗਬੀਰ',
    meaning: 'Brave Sword, Gallant Warrior',
    urduMeaning: 'بہادر شمشیر زن، تلوار کا شیر، نڈر مجاہد',
    gender: 'boy',
    startLetter: 'T',
    rashi: 'Kanya (Virgo)',
    nakshatra: 'Hasta',
    personalityEffect: 'Imparts intense courage, focus, and technical precision. The child has quick hands, great athletic capabilities, and stands firmly against injustice.',
    urduPersonalityEffect: 'Bhadri aur jalal ka sitara hai. Bacha dushman ke same datne wala aur insaf pasand hota hai. Khel kood aur hifazat mein outstanding hota hai.',
    isPopular2026: true
  },
  {
    id: '10',
    name: 'Sehaj',
    punjabiName: 'ਸਹਿਜ',
    meaning: 'State of Peace, Equilibrium, Intuitive grace',
    urduMeaning: 'سہج، سکون اور اطمینان کی حالت، روحانی اطمینan',
    gender: 'unisex',
    startLetter: 'S',
    rashi: 'Kumbha (Aquarius)',
    nakshatra: 'Shatabhisha',
    personalityEffect: 'Brings immense mental peace and an easygoing aura. Highly intuitive, mystical, and stable amidst life’s chaotic moments. Extremely wise beyond years.',
    urduPersonalityEffect: 'Bacho par nihayat thanda aur pur-skoon asar daltah hai. Mushkil halaat mein bacha ghabrata nahi aur fahasly barri durandeshi se leta hai.',
    isPopular2026: true
  },
  {
    id: '11',
    name: 'Avneet',
    punjabiName: 'ਅਵਨੀਤ',
    meaning: 'Modest, Earth-friendly, Gentle guardian',
    urduMeaning: 'خاکسار، زمین کی طرح مہربان، عاجز اور نگہبان',
    gender: 'girl',
    startLetter: 'A',
    rashi: 'Mesha (Aries)',
    nakshatra: 'Aswini',
    personalityEffect: 'Blessed with speedy dynamic recovery and a joyous heart. Influenced by Venus and planet Mars, she possesses radiant beauty and is natural solver of problems.',
    urduPersonalityEffect: 'Rohani tawanaee aur tez-fehmi ki malik hoti hai. Har kaam ko jald samajh lena aur doston mein behtreen mashwara dena iska khas asar hai.',
    isPopular2026: false
  },
  {
    id: '12',
    name: 'Simran',
    punjabiName: 'ਸਿਮਰਨ',
    meaning: 'Remembrance of God, Meditation, Focus',
    urduMeaning: 'خدا کی یاد، ذکر، عبادت، یکسوئی اور دھیان لگانا',
    gender: 'unisex',
    startLetter: 'S',
    rashi: 'Kumbha (Aquarius)',
    nakshatra: 'Purvabhadrapada',
    personalityEffect: 'Increases memory retention, spiritual focus, and academic excellence. Instills a comforting, lovable, and loyal nature towards family.',
    urduPersonalityEffect: 'Yaddasht aur parhai ke mamle mein nihayat shandaar asar rkhta hai. Dil ka saaf, wafadar aur bazuon ki madad karne wala bacha paidah hota hai.',
    isPopular2026: true
  },
  {
    id: '13',
    name: 'Jasnaam',
    punjabiName: 'ਜਸਨਾਮ',
    meaning: 'Praised Name, Glorious reputation',
    urduMeaning: 'نامی گرامی، جس کے نام کی تعریف کی جائے، روشن نام والا',
    gender: 'boy',
    startLetter: 'J',
    rashi: 'Makar (Capricorn)',
    nakshatra: 'Shravana',
    personalityEffect: 'Governed by high social prestige. The baby grows up to be clean-hearted, holds a stellar reputation, and excels in trade, law, or public administration.',
    urduPersonalityEffect: 'Is naam se bache ko izzat o shohrat milti hai. Mansab aur adliya/karobar ke maidaan mein kamyabi ke sitare buland hote hain.',
    isPopular2026: true
  },
  {
    id: '14',
    name: 'Anhad',
    punjabiName: 'ਅਨਹਦ',
    meaning: 'Limitless, Boundless Cosmic Sound',
    urduMeaning: 'بے حد، لامتناہی، وہ کائناتی موسیقی جو کبھی ختم نہ ہو',
    gender: 'unisex',
    startLetter: 'A',
    rashi: 'Tula (Libra)',
    nakshatra: 'Swati',
    personalityEffect: 'Gives the child infinite creativity, love for arts/music, and global thinking capabilities. The child refuses to stay bound by local boundaries.',
    urduPersonalityEffect: 'Sitare Swati ke zeir-e-asar bacha bayhud zeheen aur musiqi/fanoon se shoki rthega. Kamyabi ki koi hadd nahi hoti iske sitare ke mutabiq.',
    isPopular2026: true
  },
  {
    id: '15',
    name: 'Gurbani',
    punjabiName: 'ਗੁਰਬਾਣੀ',
    meaning: 'Words of Guru, Divine Revelation',
    urduMeaning: 'گورو کے بول، سچی آواز، الہی کلام',
    gender: 'girl',
    startLetter: 'G',
    rashi: 'Kumbha (Aquarius)',
    nakshatra: 'Dhanishta',
    personalityEffect: 'A voice of melody. The child possesses soothing, harmonious vocal qualities, extreme intellect, and behaves gracefully like a spiritual anchor for the family.',
    urduPersonalityEffect: 'Awaaz mein ghina aur batton mein asr paidah hota hai. Bachi khandan ke liye sukoon aur rehmat ka zariya banti hai. Boht pyari shakhsiyat hoti hai.',
    isPopular2026: true
  },
  {
    id: '16',
    name: 'Zorawar',
    punjabiName: 'ਜ਼ੋਰਾਵਰ',
    meaning: 'Strong, Powerful, Mighty',
    urduMeaning: 'زورآور، طاقتور، زبردست قوت کا مالک (Guru Gobind Singh Ji ke sahibzada)',
    gender: 'boy',
    startLetter: 'Z',
    rashi: 'Meena (Pisces)',
    nakshatra: 'Revati',
    personalityEffect: 'Bestows powerful physical constitution and undaunted stamina. The star Jupiter ensures they fight valiantly for truth and represent absolute nobility.',
    urduPersonalityEffect: 'Sahibzada Zorawar Singh se mansoob hai. Jismani aur zahni tor par intahai taqatwar aur asool pasand shakhsiyat banti hai.',
    isPopular2026: true
  },
  {
    id: '17',
    name: 'Jaiveer',
    punjabiName: 'ਜੈਵੀਰ',
    meaning: 'Victorious Warrior, Brave Lion',
    urduMeaning: 'کامیاب بہادر، جیت کا علمبردار، نیڈر شیر',
    gender: 'boy',
    startLetter: 'J',
    rashi: 'Makar (Capricorn)',
    nakshatra: 'Uttarashada',
    personalityEffect: 'Brings immense success in legal, administrative, or competitive spheres. The baby will be highly energetic and naturally magnetic to peer groups.',
    urduPersonalityEffect: 'Zabardast ba-himmat aur kalyan-kari sitara deta hai. Bachay mein doston ko sath lekar chalne aur har fatah hasil karne ka dharmi mizaj banta hai.',
    isPopular2026: false
  },
  {
    id: '18',
    name: 'Harnoor',
    punjabiName: 'ਹਰਨੂਰ',
    meaning: 'Gift of God, Divine Light of Hari',
    urduMeaning: 'خدا کا نور، گورو کا تحفہ، ربانی روشنی',
    gender: 'girl',
    startLetter: 'H',
    rashi: 'Karka (Cancer)',
    nakshatra: 'Pushya',
    personalityEffect: 'Influenced by the auspicious Pushya nakshatra, this name ensures absolute luxury, comfort, and purity. Highly protective of relationships and family values.',
    urduPersonalityEffect: 'Sitare Pushya ki barkat se bachi ka naseeb nihayat buland hota hai. Maal o daulat aur khandan ki muhabbat mein be-misal rhti hai.',
    isPopular2026: true
  },
  {
    id: '19',
    name: 'Agamjot',
    punjabiName: 'ਅਗਮਜੋਤ',
    meaning: 'Inaccessible Divine Light, Beyond REACH',
    urduMeaning: 'وہ نور جہاں تک عقل کی رسائی نہ ہو، لامتناہی الہی روشنی',
    gender: 'unisex',
    startLetter: 'A',
    rashi: 'Mesha (Aries)',
    nakshatra: 'Krittika',
    personalityEffect: 'Promotes deep scientific curiosity and discovery mindset. The child loves to solve mysteries and often ends up in top research, technology or space fields.',
    urduPersonalityEffect: 'Gahri sooch aur tajassus rakhne wala mizaj paidah hota hai. Bacha research, science aur jadeed technology mein naya naam banata hai.',
    isPopular2026: true
  },
  {
    id: '20',
    name: 'Bani',
    punjabiName: 'ਬਾਣੀ',
    meaning: 'Guru’s Voice, Earth Goddess, Graceful speech',
    urduMeaning: 'گورو کا فرمان، میٹھے بول، زمین کی رحمت',
    gender: 'girl',
    startLetter: 'B',
    rashi: 'Vrishabha (Taurus)',
    nakshatra: 'Krittika',
    personalityEffect: 'Imparts highly convincing speech and dynamic writing abilities. Blessed with a highly attractive profile and magnetic warmth in eyes.',
    urduPersonalityEffect: 'Guftago mein mithaas aur sehar paidah hota hai. Log iski guftago sun kar asar qabool karte hain. Boht piyari aur izzatdar bachi banti hai.',
    isPopular2026: true
  },
  {
    id: '21',
    name: 'Kirpa',
    punjabiName: 'ਕਿਰਪਾ',
    meaning: 'Compassion, Blessing, Grace',
    urduMeaning: 'کرم، مہربانی، نظرِ عنایت، گورو کا فیض',
    gender: 'girl',
    startLetter: 'K',
    rashi: 'Mithuna (Gemini)',
    nakshatra: 'Punarvasu',
    personalityEffect: 'Punarvasu nakshatra ensures return of good times and divine luck. The child acts as a lucky charm for her parents, driving financial abundance.',
    urduPersonalityEffect: 'Yeh bachi waldein ke liye qismat ka darwaza kholti hai. Is naam se ghar mein rizq aur khushhali ati hai.',
    isPopular2026: false
  },
  {
    id: '22',
    name: 'Karam',
    punjabiName: 'ਕਰਮ',
    meaning: 'Divine Grace, Destiny, Action',
    urduMeaning: 'کرم، بخشش، اچھے اعمال، بخت',
    gender: 'unisex',
    startLetter: 'K',
    rashi: 'Mithuna (Gemini)',
    nakshatra: 'Mrigashira',
    personalityEffect: 'Promotes active energetic lifestyle, great curiosity for knowledge and traveling. The child has exceptional luck with long journeys and international studies.',
    urduPersonalityEffect: 'Amli aur safar-pasand mizaj banta hai. Mulk se bahar parhai karne aur aala darja sikhne ke sitare nihayat mazboot hote hain.',
    isPopular2026: true
  },
  {
    id: '23',
    name: 'Prabh',
    punjabiName: 'ਪ੍ਰਭ',
    meaning: 'Lord Master, Divine Sovereign',
    urduMeaning: 'مالک، گورو، الہی حکمران، سچا ربط',
    gender: 'boy',
    startLetter: 'P',
    rashi: 'Kanya (Virgo)',
    nakshatra: 'Chitra',
    personalityEffect: 'Brings highly structured, disciplined mindset and analytical genius. Perfect for high-profile banking, software engineering, or mathematical ventures.',
    urduPersonalityEffect: 'Nihayat ba-asool aur parhai mein tez zahan ka malik banta hai. Shuru se hi zimmedar aur serious mizaj ka hamil hota hai.',
    isPopular2026: false
  },
  {
    id: '24',
    name: 'Rhea',
    punjabiName: 'ਰੀਆ',
    meaning: 'Singer, Graceful water flow, Flow of love',
    urduMeaning: 'نوا گانے والی، پانی کا بہاؤ، محبت کی روانی',
    gender: 'girl',
    startLetter: 'R',
    rashi: 'Tula (Libra)',
    nakshatra: 'Vishakha',
    personalityEffect: 'Gives the child highly charming, lively, and optimistic energy. Blessed with high networking skills and always surrounded by good friends.',
    urduPersonalityEffect: 'Behad khush-mizaj aur sargarmiyo wala mizaj. Is bachi ke doston ka halka boht wasee hota hai aur wo khushyan bikhrati hai.',
    isPopular2026: true
  }
];

export const SIKH_ALPHABETS = [
  'A', 'B', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'M', 'N', 'P', 'R', 'S', 'T', 'Z'
];

export const RASHIS = [
  { name: 'Mesha (Aries)', element: 'Fire', lord: 'Mars (Mreekh)', letters: 'A, L, I, E' },
  { name: 'Vrishabha (Taurus)', element: 'Earth', lord: 'Venus (Zuhra)', letters: 'B, V, U' },
  { name: 'Mithuna (Gemini)', element: 'Air', lord: 'Mercury (Utarid)', letters: 'K, C, G' },
  { name: 'Karka (Cancer)', element: 'Water', lord: 'Moon (Qamar)', letters: 'D, H' },
  { name: 'Simha (Leo)', element: 'Fire', lord: 'Sun (Shams)', letters: 'M, T' },
  { name: 'Kanya (Virgo)', element: 'Earth', lord: 'Mercury (Utarid)', letters: 'P, T, S' },
  { name: 'Tula (Libra)', element: 'Air', lord: 'Venus (Zuhra)', letters: 'R, T' },
  { name: 'Vrishchika (Scorpio)', element: 'Water', lord: 'Mars/Pluto', letters: 'N, Y' },
  { name: 'Dhanu (Sagittarius)', element: 'Fire', lord: 'Jupiter (Mushtari)', letters: 'F, D, B' },
  { name: 'Makar (Capricorn)', element: 'Earth', lord: 'Saturn (Zuhal)', letters: 'K, J' },
  { name: 'Kumbha (Aquarius)', element: 'Air', lord: 'Saturn (Zuhal)', letters: 'S, G' },
  { name: 'Meena (Pisces)', element: 'Water', lord: 'Jupiter (Mushtari)', letters: 'D, Z, C' }
];

export const NAKSHATRAS = [
  'Ashwini', 'Bharani', 'Krittika', 'Rohini', 'Mrigashira', 'Ardra', 'Punarvasu', 
  'Pushya', 'Ashlesha', 'Magha', 'Purvaphalguni', 'Uttaraphalguni', 'Hasta', 
  'Chitra', 'Swati', 'Vishakha', 'Shravana', 'Dhanishta', 'Shatabhisha',
  'Purvabhadrapada', 'Revati'
];
